#!/usr/bin/env bash
# This is a launcher for go-mtpfs

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

# Make necessary runtime changes to make the snap work
#export IMPORTANT_ENVIRONMENT_VARIABLE=value

# Finally run the launching command
exec "${@}"
